### ISSUE TITLE
Exception from HRESULT: 0x8007000B

### ISSUE THREAD

**Issue by petrasvestartas** [fel88/DeepNestPort#2]
Hi,

I am trying to implement your library is my software, and I get error:
1. Solution exception:An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

I really need to run the code on 64 bit, as I cannot load native code minkowski.dll that is 32 bit (I assume it is) on 64 bit environment (I assume this is the main error).

Is there any way to compile it under 64 bits?

**Comment by fel88** [comment]
Yes, you can compile minkowski.dll under 64 bits. Just switch compiler like this:
![image](https://user-images.githubusercontent.com/15663687/48504036-d7c97080-e854-11e8-936d-c08060604960.png)

**Comment by petrasvestartas** [comment]
Thank you for reply. I am trying to do this for an hour in visual studio 2017 command prompt.
Do you have any idea why it says:
_C:\Program was unexpected at this time._

![aa](https://user-images.githubusercontent.com/18013985/48507393-1c9cd980-e84c-11e8-83a6-e12b2c8d7574.png)

**Comment by fel88** [comment]
1. I think, 'System32' folder appears because you run cmd as administrator
2. Try this https://stackoverflow.com/questions/43372235/vcvarsall-bat-for-visual-studio-2017/43570522
3. Try this https://stackoverflow.com/questions/42794845/visual-studio-community-2017-cl-exe
4. Or you can try this x64 dll version [minkowski.zip](https://github.com/fel88/DeepNestPort/files/2582362/minkowski.zip)

**Comment by dharani811** [comment]
@fel88 :   Thank you man, it works like a charm.

               But sometimes on my other PC it produces SEH exception while Calling MinKowski.setData() , i clearly know that the exception happens in Minkowski.dll but i dunno how to solve this. It works perfectly fine in one PC but on the other it throws this exception. Can you help, If Possible!
