### ISSUE TITLE
SEH exception in Minkowski.dll while calling CalculateNFP()

### ISSUE THREAD

**Issue by dharani811** [fel88/DeepNestPort#3]
@fel88 :   Thank you man, it works like a charm.

But sometimes on my other PC it produces SEH exception while Calling MinKowski.CalculateNFP() , i clearly know that the exception happens in Minkowski.dll but i dunno how to solve this. It works perfectly fine in one PC but on the other it throws this exception. Can you help, If Possible!

**Comment by petrasvestartas** [comment]
I just install fresh copy on another computer, on my own it works perfectly, but on another that has totally the same architecture and softwares produces an error:

Solution exception:An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

Since it is 64 bit version I believe it simply cannot find minkowski.dll

What can cause this problem?

**Comment by fel88** [comment]
@petrasvestartas ,

> Would it work on computers that has no boost and no visual studio installed (I assume all functions of boost are placed within minkowski.dll)?

Yes, it would work. Boost and Visual studio are not required (.NET 4.0 only).

Did you switch platrofrm target of all (DeepNestPort, MinkowskiWrapper, DeepNestLib) visual studio projects to x64?

![image](https://user-images.githubusercontent.com/15663687/48556351-ca63c300-e8f4-11e8-976d-ee5ac14edcb7.png)

**Comment by petrasvestartas** [comment]
Yes it is all x64,  the only thing that is different is the .net framework which is 4.5, I will try to lower it to 4.0

**Comment by fel88** [comment]
Can you give me zip archive with your files?

**Comment by petrasvestartas** [comment]
Solved it. It was not minkowski.dll and not even the library as console application was running well on three computers. The was a stupid option marked on Rhino Software that does not allow to load unsafe native code. Now it runs perfectly. I will upload the project to GitHub so it would be easier to communicate and post direct link to this repository. This library is so good... Thank you.

**Comment by fel88** [comment]
Ok, glad to help

**Comment by dharani811** [comment]
> @dharani811 , try to simplify compile command and then recompile dll
> 
> ```
> cl /Ox -I <boost_1.62_path> /LD minkowski.cc
> ```

@fel88 : It worked, Though there are few bugs but compared to my project this is awesome.Anyhow i will share my work here once i upload to github. Once again thank you and much appreciated.

**Comment by dharani811** [comment]
@fel88 :  Here is my version of Nesting that currently am developing.

https://github.com/dharani811/NestingCShaprt

**Comment by petrasvestartas** [comment]
Dear @fel88 
I uploaded Rhino implementation and posted the link to you github page since the code is made by you and I just implemented it in Rhino:
https://github.com/petrasvestartas/OpenNest

I would like to ask if there any way to nest not to rectangle shape but arbitrary polyline? 
And is there a possibility to nest objects with holes?

**Comment by fel88** [comment]
> I would like to ask if there any way to nest not to rectangle shape but arbitrary polyline?

Yes, it is possible (but there are some bugs now). Just add not rectangle part and then choose 'move to sheets'
![image](https://user-images.githubusercontent.com/15663687/48628479-5561bd80-e9c8-11e8-9a2a-396dec91ac75.png)

> And is there a possibility to nest objects with holes?

Yes. But my svg files are without holes. 

I'll add svg samples with holes and fix bugs about not rectangle shapes soon.
